### ISSUE TITLE
ImportError: No module named 'bs4'

### ISSUE THREAD

**Issue by aj07mm** [EricksonDouglas/Pysine#4]
(pysine)➜  Pysine git:(master) python3 pysine.py -e Estagiario --cidades Crato/CE 
Traceback (most recent call last):
  File "pysine.py", line 28, in <module>
    from bs4            import BeautifulSoup
ImportError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pysine.py", line 34, in <module>
    '''+Colorir.ENDC)
NameError: name 'Colorir' is not defined

**Comment by EricksonDouglas** [comment]
Tem que instalar a lib BeautifulSoup para funcionar
comando: pip install -r requisitos.txt
